spring:
  application:
    name: banking
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5010/BaseDatos}
    username: ${SPRING_DATASOURCE_USERNAME:boris12}
    password: ${SPRING_DATASOURCE_PASSWORD:boris}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
#  sql:
#    init:
#      mode: ${SPRING_SQL_INIT_MODE:always}

logging:
  level:
    io.netty: INFO
    reactor.netty: INFO
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    tomcat: WARN
    org:
      apache:
        kafka: ERROR
      hibernate: ERROR
      springframework.web: INFO
      springframework.web.reactive: DEBUG
      springframework.web.servlet.DispatcherServlet: INFO
      springframework.web.bind: DEBUG
      springframework.web.validation: DEBUG
      springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
      springframework.boot.actuate.endpoint.web.servlet: WARN
      springframework.web.kafka: ERROR

sendLog: true


#spring:
#  application:
#    name: banking
#  datasource:
#    url: jdbc:postgresql://localhost:5010/BaseDatos
#    username: boris12
#    password: boris
#  jpa:
#    hibernate:
#      ddl-auto: create
#logging:
#  level:
#    io.netty: INFO
#    reactor.netty: INFO
#    reactor.netty.http.client: DEBUG
#    reactor.netty.http.server: DEBUG
#    tomcat: WARN
#    org:
#      apache:
#        kafka: ERROR
#      hibernate: ERROR
#      springframework.web: INFO
#      springframework.web.reactive: DEBUG
#      springframework.web.servlet.DispatcherServlet: INFO
#      springframework.web.bind: DEBUG
#      springframework.web.validation: DEBUG
#      springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
#      springframework.boot.actuate.endpoint.web.servlet: WARN
#      springframework.web.kafka: ERROR
#sendLog: true
